In [23]:
import pandas as pd
import numpy as np

In [24]:
df = pd.read_csv(r"C:\Documents\Data analytics\projects\my-data-project\SaaS project\Raw data\ravenstack_churn_events.csv")

In [25]:
df_copy = df.copy()

In [26]:
df_copy.head()

,churn_event_id,account_id,churn_date,reason_code,refund_amount_usd,preceding_upgrade_flag,preceding_downgrade_flag,is_reactivation,feedback_text
0,C-816288,A-c37cab,2024-10-27,pricing,4.03,False,False,False,switched to competitor
1,C-5a81e7,A-37f969,2024-06-25,support,96.45,True,False,False,NaN
2,C-a174be,A-b07346,2024-11-12,budget,0.00,False,False,False,missing features
3,C-accb39,A-1e50e0,2023-11-01,budget,54.94,False,False,False,switched to competitor
4,C-92f889,A-956988,2024-12-30,unknown,0.00,False,True,True,too expensive

In [27]:
df_copy.shape

(600, 9)

In [28]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   churn_event_id            600 non-null    object
 1   account_id                600 non-null    object
 2   churn_date                600 non-null    object
 3   reason_code               600 non-null    object
 4   refund_amount_usd         600 non-null    float64
 5   preceding_upgrade_flag    600 non-null    bool
 6   preceding_downgrade_flag  600 non-null    bool
 7   is_reactivation           600 non-null    bool
 8   feedback_text             452 non-null    object
dtypes: bool(3), float64(1), object(5)
memory usage: 30.0+ KB

In [29]:
df_copy.isna().sum()

churn_event_id                0
account_id                    0
churn_date                    0
reason_code                   0
refund_amount_usd             0
preceding_upgrade_flag        0
preceding_downgrade_flag      0
is_reactivation               0
feedback_text               148
dtype: int64

In [30]:
df_copy.columns = df_copy.columns.str.lower().str.replace(' ', '_')

In [31]:
none_values = ['nan', 'null', 'n/a', 'na', '', 'none', 'None', 'N/A', 'NULL', ' NAN', 'NaN']

df_copy = df_copy.replace(none_values, np.nan)
df_copy.isna().sum()

churn_event_id                0
account_id                    0
churn_date                    0
reason_code                   0
refund_amount_usd             0
preceding_upgrade_flag        0
preceding_downgrade_flag      0
is_reactivation               0
feedback_text               148
dtype: int64

In [32]:
DTYPE_MAP = {
    "churn_event_id": "string",
    "account_id": "string",
    "churn_date": "datetime64[ns]",
    "reason_code": "string",
    "refund_amount_usd": "float64",
    "preceding_upgrade_flag": "bool",
    "preceding_downgrade_flag": "bool",
    "is_reactivation": "bool",
    "feedback_text": "string",
}
df_copy = df_copy.astype(DTYPE_MAP)
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   churn_event_id            600 non-null    string
 1   account_id                600 non-null    string
 2   churn_date                600 non-null    datetime64[ns]
 3   reason_code               600 non-null    string
 4   refund_amount_usd         600 non-null    float64
 5   preceding_upgrade_flag    600 non-null    bool
 6   preceding_downgrade_flag  600 non-null    bool
 7   is_reactivation           600 non-null    bool
 8   feedback_text             452 non-null    string
dtypes: bool(3), datetime64[ns](1), float64(1), string(4)
memory usage: 30.0 KB

In [33]:
df_copy['churn_date'] = pd.to_datetime(df_copy['churn_date'])
df_copy.isna().sum()
df_copy.shape

(600, 9)

In [34]:
df_copy['churn_event_id'] = df_copy['churn_event_id'].str.strip().str.lower().str.replace('-', '')
df_copy['churn_event_id'].sample(5)

422    c249af9
333    c23d5a9
363    c9d9bff
41     cf72425
518    c0340b2
Name: churn_event_id, dtype: string

In [35]:
df_copy['account_id'] = df_copy['account_id'].str.strip().str.lower().str.replace('-', '')
df_copy['account_id'].sample(5)

334    a855a48
176    ae351e1
206    a2d4502
80     a180abf
316    a8e47ca
Name: account_id, dtype: string

In [36]:
df_copy['reason_code'] = df_copy['reason_code'].str.strip().str.lower()
df_copy['reason_code'].sample(15)

120       pricing
440    competitor
137    competitor
331      features
545    competitor
406       unknown
68     competitor
134      features
550      features
214      features
202        budget
81         budget
305       pricing
145        budget
577       support
Name: reason_code, dtype: string

In [37]:
df_copy['refund_amount_usd'].sample(20)

396     0.00
474     0.00
276     0.00
141     0.00
51     47.06
8       0.00
231     0.00
234     0.00
267    21.17
29     98.48
261     0.00
317     0.00
116     0.00
16     43.53
519     0.00
123     0.00
502     0.00
585     0.00
26      0.00
150     0.00
Name: refund_amount_usd, dtype: float64

In [38]:
df_copy['feedback_text'].sample(20)

101    switched to competitor
179          missing features
476    switched to competitor
24     switched to competitor
444             too expensive
26                       <NA>
2            missing features
156             too expensive
234    switched to competitor
151    switched to competitor
421          missing features
391    switched to competitor
477    switched to competitor
400                      <NA>
470             too expensive
172          missing features
431                      <NA>
86              too expensive
268                      <NA>
349             too expensive
Name: feedback_text, dtype: string

In [39]:
df_copy['feedback_text'].isna().sum()

np.int64(148)

In [40]:
df_copy.to_csv('C:\Documents\Data analytics\projects\my-data-project\SaaS project\Analysis\cleaned_csvs\churn_events_cleaned_2.csv', index=False)

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\PC\AppData\Local\Temp\ipykernel_14608\1598276197.py:1: SyntaxWarning: invalid escape sequence '\D'
  df_copy.to_csv('C:\Documents\Data analytics\projects\my-data-project\SaaS project\Analysis\cleaned_csvs\churn_events_cleaned_2.csv', index=False)

In [41]:
df_copy.head(10)

,churn_event_id,account_id,churn_date,reason_code,refund_amount_usd,preceding_upgrade_flag,preceding_downgrade_flag,is_reactivation,feedback_text
0,c816288,ac37cab,2024-10-27,pricing,4.03,False,False,False,switched to competitor
1,c5a81e7,a37f969,2024-06-25,support,96.45,True,False,False,<NA>
2,ca174be,ab07346,2024-11-12,budget,0.00,False,False,False,missing features
3,caccb39,a1e50e0,2023-11-01,budget,54.94,False,False,False,switched to competitor
4,c92f889,a956988,2024-12-30,unknown,0.00,False,True,True,too expensive
5,ca8ac26,ab20d99,2024-03-04,features,0.00,False,False,False,missing features
6,c2e2966,a526d93,2024-07-10,features,34.40,True,False,False,<NA>
7,cee531b,a751bd4,2024-09-22,budget,0.00,False,False,False,<NA>
8,ce6a0f0,accabf0,2024-10-31,features,0.00,False,False,False,too expensive
9,c9328ba,a0a62f5,2024-10-10,features,0.00,False,False,False,switched to competitor