In [5]:
import pandas as pd
import numpy as np

In [6]:
from pathlib import Path

base = Path.cwd()
data_path = base / 'Raw data' / 'ravenstack_accounts.csv'
if not data_path.exists():
    data_path = base.parent / 'Raw data' / 'ravenstack_accounts.csv'

df = pd.read_csv(data_path)
df.head()
df.tail()

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats,is_trial,churn_flag
495,A-8ae3fc,Company_495,DevTools,CA,2024-06-28,ads,Pro,9,False,False
496,A-55f257,Company_496,FinTech,US,2023-12-21,organic,Basic,9,False,False
497,A-d26ab4,Company_497,DevTools,UK,2024-11-07,organic,Basic,9,False,True
498,A-712533,Company_498,EdTech,US,2023-07-31,organic,Pro,18,False,False
499,A-781cc0,Company_499,EdTech,US,2024-09-04,organic,Pro,12,False,False

In [7]:
df.head()

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats,is_trial,churn_flag
0,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False
1,A-43a9e3,Company_1,FinTech,IN,2023-08-17,other,Basic,18,False,True
2,A-0a282f,Company_2,DevTools,US,2024-08-27,organic,Basic,1,False,False
3,A-1f0ac7,Company_3,HealthTech,UK,2023-08-27,other,Basic,24,True,False
4,A-ce550d,Company_4,HealthTech,US,2024-10-27,event,Enterprise,35,False,True

In [8]:
df_copy = df.copy()

In [9]:
df_copy.columns = df_copy.columns.str.strip().str.lower().str.replace(' ', '_')
df_copy.columns

Index(['account_id', 'account_name', 'industry', 'country', 'signup_date',
       'referral_source', 'plan_tier', 'seats', 'is_trial', 'churn_flag'],
      dtype='object')

In [10]:
df_copy.info()
df_copy.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   account_id       500 non-null    object
 1   account_name     500 non-null    object
 2   industry         500 non-null    object
 3   country          500 non-null    object
 4   signup_date      500 non-null    object
 5   referral_source  500 non-null    object
 6   plan_tier        500 non-null    object
 7   seats            500 non-null    int64
 8   is_trial         500 non-null    bool
 9   churn_flag       500 non-null    bool
dtypes: bool(2), int64(1), object(7)
memory usage: 32.4+ KB

account_id         object
account_name       object
industry           object
country            object
signup_date        object
referral_source    object
plan_tier          object
seats               int64
is_trial             bool
churn_flag           bool
dtype: object

In [11]:
df_copy = df_copy.apply(lambda s: s.str.strip() if s.dtype == "object" else s)

dtype_map = {
    "account_id": "string",
    "account_name": "string",
    "industry": "category",
    "country": "string",
    "signup_date": "datetime64[ns]",
    "referral_source": "category",
    "plan_tier": "category",
    "seats": "int64",
    "is_trial": "bool",
    "churn_flag": "bool",
}
df_copy = df_copy.astype(dtype_map)
df_copy["signup_date"] = pd.to_datetime(df_copy["signup_date"])
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   account_id       500 non-null    string
 1   account_name     500 non-null    string
 2   industry         500 non-null    category
 3   country          500 non-null    string
 4   signup_date      500 non-null    datetime64[ns]
 5   referral_source  500 non-null    category
 6   plan_tier        500 non-null    category
 7   seats            500 non-null    int64
 8   is_trial         500 non-null    bool
 9   churn_flag       500 non-null    bool
dtypes: bool(2), category(3), datetime64[ns](1), int64(1), string(3)
memory usage: 22.6 KB

In [12]:
missing_values = ["n/a", "na", "--", "", "null", "None", "NaN", "nan", "Null", "N/A", "NULL"]
df_copy = df_copy.replace(missing_values, np.nan)

In [13]:
df_copy.isna().sum().sort_values(ascending=False)

account_id         0
account_name       0
industry           0
country            0
signup_date        0
referral_source    0
plan_tier          0
seats              0
is_trial           0
churn_flag         0
dtype: int64

In [14]:
df_copy['account_id'] = df_copy['account_id'].str.strip().str.lower().str.replace('-', '')
df_copy['account_id'].unique()

<StringArray>
['a2e4581', 'a43a9e3', 'a0a282f', 'a1f0ac7', 'ace550d', 'a1b9609', 'aa0ca4e',
 'ae5d6ab', 'a7dacce', 'a10b8da',
 ...
 'ad3c88e', 'accb686', 'a118f1c', 'a0e966d', 'ab9f5b1', 'a8ae3fc', 'a55f257',
 'ad26ab4', 'a712533', 'a781cc0']
Length: 500, dtype: string

In [15]:
df_copy['account_name'] = df_copy['account_name'].str.strip().str.upper().str.replace('_', '')
df_copy['account_name'].sample(20)

25      COMPANY25
108    COMPANY108
466    COMPANY466
147    COMPANY147
44      COMPANY44
316    COMPANY316
230    COMPANY230
283    COMPANY283
326    COMPANY326
331    COMPANY331
28      COMPANY28
245    COMPANY245
162    COMPANY162
81      COMPANY81
48      COMPANY48
440    COMPANY440
269    COMPANY269
167    COMPANY167
50      COMPANY50
97      COMPANY97
Name: account_name, dtype: string

In [16]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   account_id       500 non-null    string
 1   account_name     500 non-null    string
 2   industry         500 non-null    category
 3   country          500 non-null    string
 4   signup_date      500 non-null    datetime64[ns]
 5   referral_source  500 non-null    category
 6   plan_tier        500 non-null    category
 7   seats            500 non-null    int64
 8   is_trial         500 non-null    bool
 9   churn_flag       500 non-null    bool
dtypes: bool(2), category(3), datetime64[ns](1), int64(1), string(3)
memory usage: 22.6 KB

In [17]:
df_copy['account_name'] = df_copy['account_name'].str.strip().str.lower().str.replace(' ', '_')
df_copy['account_name'].sample(20)

39      company39
103    company103
124    company124
69      company69
67      company67
37      company37
175    company175
101    company101
409    company409
477    company477
170    company170
261    company261
211    company211
345    company345
278    company278
337    company337
186    company186
40      company40
82      company82
420    company420
Name: account_name, dtype: string

In [18]:
df_copy['churn_flag'].unique()

array([False,  True])

In [19]:
df.shape

(500, 10)

In [21]:
df_copy.duplicated().sum()

np.int64(0)

In [22]:
df_copy.to_csv('cleaned_csvs/ravenstack_cleaned_accounts.csv', index=False)